var brands = [
    "Zara",
    "Versace",
    "Gucci",
    "Armani",
    "Get",
    "G by Guess",
    "Marc by Marc Jacobs",
    "Temperley London",
    "Robert Rodriguez",
    "Contrarian",
    "Tadashi Shoji",
    "Michael Kors",
    "Adrianna Papell",
    "Asos",
    "BCBGMAXAZRIA",
    "Burberry",
    "Tadashi Shoji",
    "Acorn",
    "ADAM by Adam Lippes",
    "Adele Fado",
    "Adia Kibur",
    "adidas",
    "adidas by Stella",
    "Eddie Bauer",
    "Eddie Borgo",
    "Eight",
    "Eight Sixty",
    "Eileen Fisher",
    "Eileen West",
    "Element",
    "Kenneth Cole",
    "Kenneth Cole Reaction",
    "Kenneth Jay Lane",
    "Kensie",
    "Kenzo",
    "Kiki de Montparnasse",
    "Nanette Lepore",
    "Narciso Rodriguez",
    "Nasty Gal",
    "Natori",
    "Nautica",
    "Neiman Marcus",
    "New Era",
    "Nicole Miller",
    "Philip Stein Teslar",
    "Philipp Plein",
    "Philosophy di Alberta Ferretti",
    "Pianurastudio",
    "Piazza Sempione",
    "Pink Lotus",
    "Pinko",
    "Rag and Bone",
    "Rails",
    "Ralph Lauren",
    "Ralph Lauren Black Label",
    "Ralph Lauren Blue Label",
    "Raoul",
    "Ray-Ban",
    "Rebecca Taylor",
    "Rebel Yell",
    "RED Valentino",
    "Rory Beca",
    "Roxy",
    "Royal Robbins",
    "RVCA",
    "Sacai",
    "Spanx",
    "Sparkle & Fade",
    "Speedo",
    "Sperry",
    "Splendid",
    "St. John",
    "Stefanel",
    "Steffen Schraut",
    "Stella Jean",
    "Stella McCartney",
    "The Row",
    "The Sak",
    "Theory",
    "Victoria Beckham",
    "Victoria's Secret",
    "Vigoss",
    "Vila",
    "Vince Camuto",
    "3.1 Phillip Lim",
    "525 America",
    "6 Shore Road",
    "7 For All Mankind"
];